### ISSUE TITLE
Upstream returns "Fatal error: unknown ca" in Federation Status page of downstream Management console.

### ISSUE THREAD

**Issue by hellosmith420** [rabbitmq/rabbitmq-federation#62]
Hello,
I am setting up and federation over TLS. following is the URL pattern, I have used.
`amqps://<upstream_host>:5671?cacertfile=/path/to/ca_chain.pem&certfile=/path/to/cert.pem&keyfile=/path/to/cert.key.pem&verify=verify_peer&fail_if_no_peer_cert=true&auth_mechanism=external&password=12345678&depth=6`

And I got the above mentioned error.
Additionally, I have tried to connect upstream broker from downstream host through an erl sample script, using the same certificates used in above URL and I have successfully connected to upstream and published messages.
As both are using erlang client in background, then why the different result, I am not getting.
Following erlang script I have used to connect.

```
#!/usr/bin/env /opt/rabbitmq/erlang/19.0.4/bin/escript
-include_lib("amqp_client-3.6.9/include/amqp_client.hrl").
main(_) ->
    {ok, Connection} =
         amqp_connection:start(#amqp_params_network{host = "<host>",
                                                  auth_mechanisms = [fun amqp_auth_mechanisms:external/3],
                                                  port = 5671,
               ssl_options = [{cacertfile, "/path/to/ca_chain.pem"},
               {certfile, "/path/to/cert.pem"},
               {keyfile, "/path/to/cert.key.pem"},
               {password,              "123456"},
               {depth, 6},
               {verify, verify_peer},
               {fail_if_no_peer_cert, true}]}),

    {ok, Channel} = amqp_connection:open_channel(Connection),
    amqp_channel:call(Channel, #'queue.declare'{queue = <<"erlQ">>}),
    amqp_channel:cast(Channel,
                      #'basic.publish'{
                        exchange = <<"">>,
                        routing_key = <<"erlQ">>},
                      #amqp_msg{payload = <<"ssl">>}),
    io:format(" [x] Sent 'ssl'~n"),
    ok = amqp_channel:close(Channel),
    ok = amqp_connection:close(Connection),
    ok.
```
Thanks,
John

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
[rabbitmq-users thread](https://groups.google.com/forum/#!topic/rabbitmq-users/ijLtDXcW9y0)
