### ISSUE TITLE
Federated queue, dlq

### ISSUE THREAD

**Issue by andrevus** [rabbitmq/rabbitmq-federation#96]
Hi there,

I have deployed rabbitmq cluster (3 nodes) in two dc (I will be using names cluster1 and cluster2). I used federation plugin to transmit messages between them. Everything works fine, but recently I noticed that that there is some problem with dlq.

I have 3 exchanges 
main (topic with routing key (e.g. topic1) -> queue main)
main.dlx (topic with routing key # -> queue main.dlq)
main.dlx.retry (topic with routing key same as main -> queue main)

and 2 queues
main - (with x-dead-exchange set to main.dlx)
main.dlq (with x-dead-exchange set to main.dlx.rery and x-message-ttl is set).

Now, when consumer is connected to cluster1 and I publish message to cluster1 - everything works fine, both consuming and dlq with retry time)
When consumer is connected to cluster1 and I publish to cluster2 - I receive message (federation will work), but when I nack then with requeue set to false - message will disappear.

I noticed this in 3.6.1 version, but I prepare some code with newest version using docker and problem is still occurs.

https://github.com/andrevus/rabbitmq-federated-dlq

**Comment by michaelklishin** [comment]
If I understand the description and intent in the script correctly, you expect negative acknowledgements from any consumer across any federated node to be transparent and behave the same way it does on a single node w.r.t. nacking. That's not the case because queue federation links act as [low priority consumers](https://www.rabbitmq.com/federated-queues.html#usage).

As far as queue federation goes, dead lettering is indistinguishable for "regular" publishing. However, when a federation link moves a message in a federated queue around, it consumes it
unless there is a local consumer.

Dead lettering interactions with this additional layer of queue federation consumers can be quite difficult to reason about and monitor. I'd avoid this combination as it federated queues were not designed to be used with dead lettering for retries.
